spring.application.name=check_book

spring.datasource.url=jdbc:mysql://localhost:3306/book_check_db
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


spring.mvc.servlet.path=/api
app.jwt.secret=4b0ZkT8nFvHjX3pQsKq0wJ2zQd5d3vN5e7h8i9y0u1o2=
app.crypto.secret=D8f$7kL!2pQ@4rXy
ad.mock=true
entrust.mock=true
entrust.url=https://172.20.236.28:7851/entrust2/service
entrust.username=GUPAY
entrust.password=Waterfall

